on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build index.html file
        run: python3 build.py

      - name: upload built files
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: out/index.html